namespace: ingress-wg69

bases:
- ../../apps/ingress-nginx
resources:
- namespace.yaml
- endpoint.yaml

patches:

- path: patch-role.yaml
  target:
    kind: Role
    name: nginx-ingress-role

- path: patch-crb.yaml
  target:
    kind: ClusterRoleBinding
    name: nginx-ingress-clusterrole-nisa-binding

# rewire the service a little
- path: patch-service.yaml
  target:
    kind: Service
    name: ingress-nginx

# Configure ingress class
- path: patch-container-args.yaml
  target:
    kind: Deployment
    name: nginx-ingress-controller

# Convert into a statefulset to run exactly 1
- path: patch-to-statefulset.yaml
  target:
    kind: Deployment
    name: nginx-ingress-controller
- path: wireguard-sidecar.yaml

secretGenerator:
- name: wireguard-key
  env: wireguard.env

configMapGenerator:
- name: wireguard-conf
  files:
  - wg0.conf=wireguard.conf
