---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automaton
spec:
  template:
    spec:
      containers:
      - name: app

        args:
        - node
        - --unhandled-rejections=strict
        - /app
        - --app
        - irc
        - --service
        - irc-automaton
        - --default-mounts
        - --/irc-modem
        - skylink+http://irc-modem
        - --/coinbase-api
        - skylink+http://coinbase-api-client

        volumeMounts:
        - name: routines
          mountPath: /app/routines
      volumes:
      - name: routines
        configMap:
          name: routines-irc-746m228g76
