apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../apps/lambdabot
patchesStrategicMerge:
- node-assignment.yaml

configMapGenerator:
- name: lambdabot-config
  files:
  - lambdabot=lambdabot.rc

images:
- name: gcr.io/stardust-156404/lambdabot
  newTag: full
