---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sabnzbd-int
  annotations:
    kubernetes.io/ingress.class: wg69
    external-dns.alpha.kubernetes.io/ttl: "600"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.69.1.1/24
    cert-manager.io/cluster-issuer: wg69-issuer
spec:
  tls:
  - hosts:
    - sabnzbd.int.wg69.net
    secretName: tls-sabnzbd.int.wg69.net
  rules:
  - host: sabnzbd.int.wg69.net
    http:
      paths:
      - path: /
        backend:
          serviceName: usenet
          servicePort: sabnzbd
  - host: sabnzbd.wg69.elrod.me
    http:
      paths:
      - path: /
        backend:
          serviceName: usenet
          servicePort: sabnzbd
