---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: conduit-api-fe
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "60"
    kubernetes.io/ingress.class: internet
    cert-manager.io/issuer: letsencrypt-prod
spec:

  tls:
  - hosts:
    - conduit.wg69.net
    secretName: tls-conduit.wg69.net

  rules:
  - host: conduit.wg69.net
    http:
      paths:
      - path: /
        backend:
          serviceName: conduit-api-server
          servicePort: 80
